### ISSUE TITLE
deadvars removes live variable

### ISSUE THREAD

**Issue by LukeXuan** [PrincetonUniversity/VST#302] opened 2018-12-09 22:29 UTC
See [index_string.c:565](https://github.com/PrincetonUniversity/DeepSpecDB/blob/4cdf830b935be230fa0a450df05d4160776f72ec/src/index_string.c#L565), when I call deadvars between line 572 and 576, variable `v` will always be removed which shouldn't happen (but not before or after the lines).

I will try produce a smaller example later.

**Comment by andrew-appel** [comment] 2023-01-31 20:05
Not able to reproduce this, and no one has re-reported it in 5 years, so I'm closing it now.  (And it's not a soundness bug...)

**Closed by andrew-appel** 2023-01-31 20:05 UTC
