### ISSUE TITLE
rewrite of length may be dangerous

### ISSUE THREAD

**Issue by bcip** [PrincetonUniversity/VST#382] opened 2020-01-09 05:05 UTC
Consider the following example.
```
Require Import VST.floyd.proofauto.

Example bug : forall X i (al bl : list X),
  i < Zlength al ->
  Zlength (sublist 0 i (al ++ bl)) <= i ->
  Zlength (sublist 0 i (al ++ bl)) <= i.
Proof.
  intros.
  Zlength_solve.
Abort.

Example bug : forall X i (al bl : list X),
  i < Zlength al ->
  Zlength (sublist 0 i (al ++ bl)) <= i ->
  Zlength (sublist 0 i (al ++ bl)) <= i.
Proof.
  intros.
  autorewrite with Zlength in H0.
  Fail Zlength_solve.
  Fail list_solve.
Abort.

Example bug : forall X i (al bl : list X),
  i < Zlength al ->
  Zlength (sublist 0 i (al ++ bl)) <= i ->
  Zlength (sublist 0 i (al ++ bl)) <= i.
Proof.
  intros.
  autorewrite with sublist in H0.
  Fail Zlength_solve.
  Fail list_solve.
Abort.
```
The first attempt looks good.
But in the second attempt, after simplifying Zlength in premises,
`Zlength (sublist 0 i (al ++ bl)) <= i` becomes `i - 0 <= i`.
And we lost the information `0 <= i`.
Then the goal becomes unprovable (at least unprovable by `Zlength_solve` or `list_solve`).
The third attempt shows the same problem for `autorewrite with sublist`.

**Comment by andrew-appel** [comment] 2020-05-04 17:55
I am not sure that this is a bug.  Shall we decide whether it is a bug?  And if it is not a bug, let's close this issue.

**Comment by bcip** [comment] 2020-05-05 16:44
@andrew-appel I think it is a bug, because list_simplify should not turn a provable goal to an unprovable goal, even in this corner case. The example shows the assumption needed to rewrite `Zlength (sublist 0 i (al ++ bl))` is `0 <= i <= Zlength (al ++ bl)`. But the side `0 <= i` is actually proved by `Zlength (sublist 0 i (al ++ bl)) <= i`. After replacing `Zlength (sublist 0 i (al ++ bl))` with `i - 0` in `H0`, we lose the information `0 <= i`.

Technically, this issue is resolved in the new version of list solver, because it always remembers what is rewritten. So we have `Zlength_fact (Zlength (sublist 0 i (al ++ bl)) = i - 0)` which actually keeps the information `0 <= i`. But we didn't tell users about this possibility. They still think the goal is unprovable in this case.

**Comment by andrew-appel** [comment] 2020-05-05 17:19
How about this solution:
In the `sublist` hint database, put `Zlength_sublist`, but in the internal rewriting you do for list_solve, use `Zlength_sublist2`.

**Comment by andrew-appel** [comment] 2020-05-06 10:50
Resolved by putting a warning in the reference manual.

**Closed by andrew-appel** 2020-05-06 10:50 UTC
