### ISSUE TITLE
Bad pretty-printing for `->`

### ISSUE THREAD

**Issue by QinshiWang** [PrincetonUniversity/VST#594] opened 2022-06-27 15:41 UTC
Without importing VST,
```coq
Lemma foo : nat -> nat.
```
It prints
```
1 goal
______________________________________(1/1)
nat -> nat
```
After importing VST,
```coq
Require Import VST.floyd.proofauto.
Lemma foo : nat -> nat.
```
It prints
```
1 goal
______________________________________(1/1)
nat->nat
```
#### Version
VST commit 8ff48be92e1be3df3cc7a1959852935792ba168c
Coq 8.15.1

**Comment by andrew-appel** [comment] 2022-07-01 17:01
See Coq issue 16262, referenced just above.   It's caused by floyd/Clightnotations.v, the `Notation "p_val -> f_val"` command. It could perhaps be fixed by removing the "format" specifier from that line, assuming that fix doesn't break anything else.

**Closed** 2022-07-08 06:47 UTC
