### ISSUE TITLE
Broken on Coq master 

### ISSUE THREAD

**Issue by SkySkimmer** [PrincetonUniversity/VST#369] opened 2019-09-28 15:36 UTC
eg https://gitlab.com/coq/coq/-/jobs/304581187
~~~

File "./veric/semax_call.v", line 1329, characters 7-13:
Error:
In environment
CS : compspecs
Espec : OracleKind
Delta : tycontext
A : TypeTree
P : forall ts : list Type, dependent_type_functor_rec ts (AssertTT A) mpred
Q : forall ts : list Type, dependent_type_functor_rec ts (AssertTT A) mpred
NEP : super_non_expansive P
NEQ' : super_non_expansive Q
ts : list Type
x : dependent_type_functor_rec ts A mpred
F : environ -> pred rmap
F0 : assert
ret : option ident
curf : function
fsig : funsig
cc : calling_convention
R : ret_assert
psi : genv
vx : env
tx : temp_env
k : cont
rho : environ
ora : OK_ty
b : block
jm : juicy_mem
Hora : ext_compat ora (m_phi jm)
TCret : tc_fn_return Delta ret (snd fsig)
TC3 : guard_environ Delta curf rho
TC5 : snd fsig = Tvoid -> ret = None
H : closed_wrt_vars (thisvar ret) F0
HGG : cenv_sub cenv_cs psi
H0 : rho = construct_rho (filter_genv psi) vx tx
H1 : rguard Espec psi Delta curf (frame_ret_assert R F0) k (level (m_phi jm))
H4 : funassert Delta rho (m_phi jm)
Prog_OK : believe Espec Delta psi Delta (level jm)
args : list val
H14 :
(F0 rho * F rho * P ts x (make_args (map fst (fst fsig)) args rho))%pred
  (m_phi jm)
H5 :
believe_external Espec psi (Vptr b Ptrofs.zero) fsig cc A P Q (S (level jm))
The term "fundef" has type "Type -> Type" which should be Set, Prop or Type.

Makefile:423: recipe for target 'veric/semax_call.vo' failed
~~~

**Comment by SkySkimmer** [comment] 2019-09-28 15:38
See also https://github.com/coq/coq/pull/10799

**Comment by lennartberinger** [comment] 2019-09-28 17:38
I can't reproduce the error under Coq 8.10+alpha but the
error message suggests that the run on gitlab resolved 
fundef to AST.fundef rather than Clight.fundef. I've
committed a version with the correctly qualified name.

Lennart.


----- Original Message -----

**Comment by SkySkimmer** [comment] 2019-09-29 18:41
Now there's the same error line 2620

**Comment by lennartberinger** [comment] 2019-09-29 20:36
I just added the qualifier in several other places in veric. Hope it now works.

Lennart.


----- Original Message -----

**Comment by ejgallego** [comment] 2020-03-08 07:44
This should be closed, note however that `master` seems broken again.

**Closed** 2020-05-04 14:55 UTC
